repo:
  public: php-server-sdk
  private: php-server-sdk-private

publications:
  - url: https://packagist.org/packages/launchdarkly/server-sdk
    description: Packagist

circleci:
  linux:
    image: ldcircleci/ld-php-sdk-release:1  # built in sdks-ci-docker project, contains PHP 7.2 + phpDocumentor

documentation:
  githubPages: true

sdk:
  displayName: "PHP"
