version: 2

repo:
  public: php-server-sdk
  private: php-server-sdk-private

publications:
  - url: https://packagist.org/packages/launchdarkly/server-sdk
    description: Packagist

jobs:
  - docker:
      image: ldcircleci/php-sdk-release:4  # Releaser's default for PHP is still php-sdk-release:3, which is PHP 7.x
    template:
      name: php

documentation:
  gitHubPages: true
  title: "LaunchDarkly PHP SDK"

sdk:
  displayName: "PHP"
